// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBigWwrMUsFkDasDJMzGAZfmFQBNsgOhog',
    appId: '1:769703360921:web:your-web-app-id',
    messagingSenderId: '769703360921',
    projectId: 'sisterhood-app-6452c',
    authDomain: 'sisterhood-app-6452c.firebaseapp.com',
    storageBucket: 'sisterhood-app-6452c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBigWwrMUsFkDasDJMzGAZfmFQBNsgOhog',
    appId: '1:769703360921:android:6fcf8117f1eb1894df3b08',
    messagingSenderId: '769703360921',
    projectId: 'sisterhood-app-6452c',
    storageBucket: 'sisterhood-app-6452c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvB-XEBQkJXca6C0cP5ISBYWDfzofJyGI',
    appId: '1:769703360921:ios:6bdc52cbf2edf37bdf3b08',
    messagingSenderId: '769703360921',
    projectId: 'sisterhood-app-6452c',
    storageBucket: 'sisterhood-app-6452c.firebasestorage.app',
    iosBundleId: 'com.example.sisterhoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvB-XEBQkJXca6C0cP5ISBYWDfzofJyGI',
    appId: '1:769703360921:ios:6bdc52cbf2edf37bdf3b08',
    messagingSenderId: '769703360921',
    projectId: 'sisterhood-app-6452c',
    storageBucket: 'sisterhood-app-6452c.firebasestorage.app',
    iosBundleId: 'com.example.sisterhoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBigWwrMUsFkDasDJMzGAZfmFQBNsgOhog',
    appId: '1:769703360921:web:your-windows-app-id',
    messagingSenderId: '769703360921',
    projectId: 'sisterhood-app-6452c',
    storageBucket: 'sisterhood-app-6452c.firebasestorage.app',
  );
}
